sudo: required
services: 
  - docker

before_install:
  - docker build -t mohammadbagwan/my-visits-app-react -f ./client/Dockerfile.dev ./client

scripts: 
  - docker run -e CI=true mohammadbagwan/my-visits-app-react npm run test -- --coverage

after_success: 
  - docker build -t mohammadbagwan/visits-app-client ./client
  - docker build -t mohammadbagwan/visits-app-server ./server
  - docker build -t mohammadbagwan/visits-app-nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push mohammadbagwan/visits-app-client
  - docker push mohammadbagwan/visits-app-server
  - docker push mohammadbagwan/visits-app-nginx

deploy:
  provider: elasticbeanstalk
  region: us-west-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-west-1-105253923141
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  